export default {
  siteName: 'BlockReducer',
  signIn: 'Sign in',
  signUp: 'Sign up',
  signOut: 'Sign out',
  home: 'Home',
  signInWithYourAccount: 'Sign in with your account',
  signUpToYourAccount: 'Sign up to your Account',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  username: 'Username',
  password: 'Password',
  invitationCode: 'Invitation Code',
  keepMeSignedIn: 'Keep me signed in',
  forgotPassword: 'Forgot password?',
  doNotHaveAnAccount: 'Do not have an account?',
  alreadyHaveAnAccount: 'Already have an account?',
  thisFieldIsRequired: 'This field is required',
  yourEmailIsInvalid: 'Your Email is invalid',
  agreeTheTermsAndPolicy: 'Agree the terms and policy',
  pleaseAcceptThis: 'Please accept this',
  refresh: 'Refresh',
  dashboard: 'Dashboard',
  priceChart: 'Price chart',
};
