export default {
  siteName: 'BlockReducer',
  noData: 'No data',
  signIn: 'Sign in',
  signUp: 'Sign up',
  signOut: 'Sign out',
  home: 'Home',
  success: 'Success',
  error: 'Error',
  unkbownServerError: 'Unknown server error',
  signInWithYourAccount: 'Sign in with your account',
  signUpToYourAccount: 'Sign up to your Account',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  username: 'Username',
  password: 'Password',
  invitationCode: 'Invitation Code',
  keepMeSignedIn: 'Keep me signed in',
  forgotPassword: 'Forgot password?',
  doNotHaveAnAccount: 'Do not have an account?',
  alreadyHaveAnAccount: 'Already have an account?',
  thisFieldIsRequired: 'This field is required',
  yourEmailIsInvalid: 'Your Email is invalid',
  agreeTheTermsAndPolicy: 'Agree the terms and policy',
  pleaseAcceptThis: 'Please accept this',
  refresh: 'Refresh',
  adminPanel: 'Admin Panel',
  userManagement: 'User Management',
  dashboard: 'Dashboard',
  general: 'General',
  priceChart: 'Price chart',
  volumeChart: 'Volume chart',
  vwapChart: 'VWAP chart',
  currentTradeChart: 'Current trade chart',
  ohlcChart: 'OHLC chart',
  hiddenOrder: 'Hidden order',
  dailyChart: 'Daily chart',
  yearlyChart: 'Yearly chart',
  volatilityChart: 'Volatility chart',
  marketSentiment: 'Market sentiment',
  linearChart: 'Linear chart',
  logarithmicChart: 'Logarithmic chart',
  exchangeInformation: 'Exchange information',
  deribitInformation: 'Deribit Information',
  option1: 'Option1',
  option2: 'Option2',
  option3: 'Option3',
  settings: 'Settings',
  builtWithCryptocurrency: 'Built with Crytocurrency',

  startTime: 'Start date',
  endTime: 'End date',
  binSize: 'Bin size',
  timezone: 'Timezone',
  submit: 'Submit',
  filter: 'Filter',

  id: 'ID',
  name: 'Name',
  url: 'URL',
  active: 'Active',

  no_: '#',
  role: 'Role',
  status: 'Status',

  symbol: 'Symbol',
  minPrice: 'Min Price',
  itemCount: 'Item Count',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  change: 'Change',
  confirmPasswordIsNotMatchWithNewPassword: 'Confirm Password is not match with new password',

  yes: 'Yes',
  no: 'No',

  deleteUser: 'Delete User',
  doYouWantToDelete: 'Do you want to delete?',

  addUser: 'Add User',
  editUser: 'Edit User',
  add: 'Add',
  edit: 'Edit',
  cancel: 'Cancel',
  thisEmailIsInvalid: 'This email is invalid',
};
